//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStore1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoffeeEntities : DbContext
    {
        public CoffeeEntities()
            : base("name=CoffeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<int>> addCartItem(Nullable<int> session_id, Nullable<int> product_id, Nullable<int> quantity, string created_by, Nullable<System.DateTime> created_at, Nullable<bool> isActive)
        {
            var session_idParameter = session_id.HasValue ?
                new ObjectParameter("session_id", session_id) :
                new ObjectParameter("session_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("addCartItem", session_idParameter, product_idParameter, quantityParameter, created_byParameter, created_atParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> addOrder_details(Nullable<int> user_id, Nullable<double> grandtotal, string addedUserName)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var grandtotalParameter = grandtotal.HasValue ?
                new ObjectParameter("grandtotal", grandtotal) :
                new ObjectParameter("grandtotal", typeof(double));
    
            var addedUserNameParameter = addedUserName != null ?
                new ObjectParameter("AddedUserName", addedUserName) :
                new ObjectParameter("AddedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("addOrder_details", user_idParameter, grandtotalParameter, addedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> addOrder_items(Nullable<int> order_id, Nullable<int> product_id, string addedUserName)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var addedUserNameParameter = addedUserName != null ?
                new ObjectParameter("AddedUserName", addedUserName) :
                new ObjectParameter("AddedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("addOrder_items", order_idParameter, product_idParameter, addedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> addpayment_details(Nullable<int> orderID, Nullable<double> grandAmount, string provider, string status, string nameonCard, string cardNumber, string expiryDateMMYY, string securityCode, string zipCode, Nullable<bool> shippingUserContactAddress, string shippingAddress, string addedUserName)
        {
            var orderIDParameter = orderID.HasValue ?
                new ObjectParameter("OrderID", orderID) :
                new ObjectParameter("OrderID", typeof(int));
    
            var grandAmountParameter = grandAmount.HasValue ?
                new ObjectParameter("GrandAmount", grandAmount) :
                new ObjectParameter("GrandAmount", typeof(double));
    
            var providerParameter = provider != null ?
                new ObjectParameter("provider", provider) :
                new ObjectParameter("provider", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var nameonCardParameter = nameonCard != null ?
                new ObjectParameter("NameonCard", nameonCard) :
                new ObjectParameter("NameonCard", typeof(string));
    
            var cardNumberParameter = cardNumber != null ?
                new ObjectParameter("CardNumber", cardNumber) :
                new ObjectParameter("CardNumber", typeof(string));
    
            var expiryDateMMYYParameter = expiryDateMMYY != null ?
                new ObjectParameter("ExpiryDateMMYY", expiryDateMMYY) :
                new ObjectParameter("ExpiryDateMMYY", typeof(string));
    
            var securityCodeParameter = securityCode != null ?
                new ObjectParameter("SecurityCode", securityCode) :
                new ObjectParameter("SecurityCode", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("zipCode", zipCode) :
                new ObjectParameter("zipCode", typeof(string));
    
            var shippingUserContactAddressParameter = shippingUserContactAddress.HasValue ?
                new ObjectParameter("ShippingUserContactAddress", shippingUserContactAddress) :
                new ObjectParameter("ShippingUserContactAddress", typeof(bool));
    
            var shippingAddressParameter = shippingAddress != null ?
                new ObjectParameter("ShippingAddress", shippingAddress) :
                new ObjectParameter("ShippingAddress", typeof(string));
    
            var addedUserNameParameter = addedUserName != null ?
                new ObjectParameter("AddedUserName", addedUserName) :
                new ObjectParameter("AddedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("addpayment_details", orderIDParameter, grandAmountParameter, providerParameter, statusParameter, nameonCardParameter, cardNumberParameter, expiryDateMMYYParameter, securityCodeParameter, zipCodeParameter, shippingUserContactAddressParameter, shippingAddressParameter, addedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> addshopping_session(Nullable<int> user_id, Nullable<double> total, string addedUserName)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(double));
    
            var addedUserNameParameter = addedUserName != null ?
                new ObjectParameter("AddedUserName", addedUserName) :
                new ObjectParameter("AddedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("addshopping_session", user_idParameter, totalParameter, addedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AddUser(string username, string password, string first_name, string last_name, string address, string city, string state, string zipCode, string telephone, string addedUserName, string modifiedUserName)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("ZipCode", zipCode) :
                new ObjectParameter("ZipCode", typeof(string));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("telephone", telephone) :
                new ObjectParameter("telephone", typeof(string));
    
            var addedUserNameParameter = addedUserName != null ?
                new ObjectParameter("AddedUserName", addedUserName) :
                new ObjectParameter("AddedUserName", typeof(string));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AddUser", usernameParameter, passwordParameter, first_nameParameter, last_nameParameter, addressParameter, cityParameter, stateParameter, zipCodeParameter, telephoneParameter, addedUserNameParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> deleteCartItem(Nullable<int> cartItemid, string modified_by)
        {
            var cartItemidParameter = cartItemid.HasValue ?
                new ObjectParameter("cartItemid", cartItemid) :
                new ObjectParameter("cartItemid", typeof(int));
    
            var modified_byParameter = modified_by != null ?
                new ObjectParameter("modified_by", modified_by) :
                new ObjectParameter("modified_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("deleteCartItem", cartItemidParameter, modified_byParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> deleteOrder_details(Nullable<int> id, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("deleteOrder_details", idParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> deleteOrder_items(Nullable<int> id, string modifiedUserName, Nullable<bool> isActive)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("deleteOrder_items", idParameter, modifiedUserNameParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> deletePayment_details(Nullable<int> id, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("deletePayment_details", idParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> deleteShopping_session(Nullable<int> id, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("deleteShopping_session", idParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> deleteUser(Nullable<int> id, string username, string password, string first_name, string last_name, string address, string telephone, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("telephone", telephone) :
                new ObjectParameter("telephone", typeof(string));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("deleteUser", idParameter, usernameParameter, passwordParameter, first_nameParameter, last_nameParameter, addressParameter, telephoneParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<SelectCartItem_1> SelectCartItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCartItem_1>("SelectCartItem");
        }
    
        public virtual ObjectResult<SelectOrder_details_1> SelectOrder_details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOrder_details_1>("SelectOrder_details");
        }
    
        public virtual ObjectResult<SelectOrder_items_1> SelectOrder_items()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectOrder_items_1>("SelectOrder_items");
        }
    
        public virtual ObjectResult<SelectPayment_details_1> SelectPayment_details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPayment_details_1>("SelectPayment_details");
        }
    
        public virtual ObjectResult<SelectProduct_1> SelectProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectProduct_1>("SelectProduct");
        }
    
        public virtual ObjectResult<SelectUser_1> SelectUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectUser_1>("SelectUser");
        }
    
        public virtual ObjectResult<shopping_session_1> shopping_session()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<shopping_session_1>("shopping_session");
        }
    
        public virtual ObjectResult<Nullable<int>> updateCartItem(Nullable<int> cartitemid, Nullable<int> quantity, string modified_by)
        {
            var cartitemidParameter = cartitemid.HasValue ?
                new ObjectParameter("cartitemid", cartitemid) :
                new ObjectParameter("cartitemid", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var modified_byParameter = modified_by != null ?
                new ObjectParameter("modified_by", modified_by) :
                new ObjectParameter("modified_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("updateCartItem", cartitemidParameter, quantityParameter, modified_byParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> updateOrder_details(Nullable<int> id, Nullable<int> user_id, Nullable<double> total, Nullable<int> payment_id, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(double));
    
            var payment_idParameter = payment_id.HasValue ?
                new ObjectParameter("payment_id", payment_id) :
                new ObjectParameter("payment_id", typeof(int));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("updateOrder_details", idParameter, user_idParameter, totalParameter, payment_idParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> updateOrder_items(Nullable<int> order_id, string modifiedUserName)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("updateOrder_items", order_idParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> updatePayment_details(Nullable<int> id, Nullable<int> order_id, Nullable<double> amount, string provider, string status, string nameonCard, string cardNumber, string expiryDateMMYY, string securityCode, string zipCode, Nullable<bool> shippingUserContactAddress, string shippingAddress, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("amount", amount) :
                new ObjectParameter("amount", typeof(double));
    
            var providerParameter = provider != null ?
                new ObjectParameter("provider", provider) :
                new ObjectParameter("provider", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var nameonCardParameter = nameonCard != null ?
                new ObjectParameter("NameonCard", nameonCard) :
                new ObjectParameter("NameonCard", typeof(string));
    
            var cardNumberParameter = cardNumber != null ?
                new ObjectParameter("CardNumber", cardNumber) :
                new ObjectParameter("CardNumber", typeof(string));
    
            var expiryDateMMYYParameter = expiryDateMMYY != null ?
                new ObjectParameter("ExpiryDateMMYY", expiryDateMMYY) :
                new ObjectParameter("ExpiryDateMMYY", typeof(string));
    
            var securityCodeParameter = securityCode != null ?
                new ObjectParameter("SecurityCode", securityCode) :
                new ObjectParameter("SecurityCode", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("zipCode", zipCode) :
                new ObjectParameter("zipCode", typeof(string));
    
            var shippingUserContactAddressParameter = shippingUserContactAddress.HasValue ?
                new ObjectParameter("ShippingUserContactAddress", shippingUserContactAddress) :
                new ObjectParameter("ShippingUserContactAddress", typeof(bool));
    
            var shippingAddressParameter = shippingAddress != null ?
                new ObjectParameter("ShippingAddress", shippingAddress) :
                new ObjectParameter("ShippingAddress", typeof(string));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("updatePayment_details", idParameter, order_idParameter, amountParameter, providerParameter, statusParameter, nameonCardParameter, cardNumberParameter, expiryDateMMYYParameter, securityCodeParameter, zipCodeParameter, shippingUserContactAddressParameter, shippingAddressParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> UpdateUser(Nullable<int> id, string username, string password, string first_name, string last_name, string address, string city, string state, string zipCode, string telephone, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zipCodeParameter = zipCode != null ?
                new ObjectParameter("ZipCode", zipCode) :
                new ObjectParameter("ZipCode", typeof(string));
    
            var telephoneParameter = telephone != null ?
                new ObjectParameter("telephone", telephone) :
                new ObjectParameter("telephone", typeof(string));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("UpdateUser", idParameter, usernameParameter, passwordParameter, first_nameParameter, last_nameParameter, addressParameter, cityParameter, stateParameter, zipCodeParameter, telephoneParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> updatShopping_session(Nullable<int> id, Nullable<int> user_id, Nullable<double> total, string provider, string status, string modifiedUserName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(double));
    
            var providerParameter = provider != null ?
                new ObjectParameter("provider", provider) :
                new ObjectParameter("provider", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var modifiedUserNameParameter = modifiedUserName != null ?
                new ObjectParameter("ModifiedUserName", modifiedUserName) :
                new ObjectParameter("ModifiedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("updatShopping_session", idParameter, user_idParameter, totalParameter, providerParameter, statusParameter, modifiedUserNameParameter);
        }
    
        public virtual ObjectResult<SelectUserValidYN_1> SelectUserValidYN(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectUserValidYN_1>("SelectUserValidYN", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> AddLog(string username, string error_Message, string addedUserName)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var error_MessageParameter = error_Message != null ?
                new ObjectParameter("Error_Message", error_Message) :
                new ObjectParameter("Error_Message", typeof(string));
    
            var addedUserNameParameter = addedUserName != null ?
                new ObjectParameter("AddedUserName", addedUserName) :
                new ObjectParameter("AddedUserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("AddLog", usernameParameter, error_MessageParameter, addedUserNameParameter);
        }
    
        public virtual ObjectResult<SelectCartItem_BySessionID_1> SelectCartItem_BySessionID(Nullable<int> sessionID)
        {
            var sessionIDParameter = sessionID.HasValue ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCartItem_BySessionID_1>("SelectCartItem_BySessionID", sessionIDParameter);
        }
    
        public virtual ObjectResult<SelectCartItemGrandTotal_BySessionID_1> SelectCartItemGrandTotal_BySessionID(Nullable<int> sessionID)
        {
            var sessionIDParameter = sessionID.HasValue ?
                new ObjectParameter("sessionID", sessionID) :
                new ObjectParameter("sessionID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectCartItemGrandTotal_BySessionID_1>("SelectCartItemGrandTotal_BySessionID", sessionIDParameter);
        }
    
        public virtual ObjectResult<SelectPayment_details_ById_1> SelectPayment_details_ById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPayment_details_ById_1>("SelectPayment_details_ById", idParameter);
        }
    
        public virtual ObjectResult<SelectUser_Byid_1> SelectUser_Byid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectUser_Byid_1>("SelectUser_Byid", idParameter);
        }
    }
}
