//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStore1
{
    using System;
    
    public partial class SelectPayment_details_ById_1
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public double amount { get; set; }
        public string provider { get; set; }
        public string status { get; set; }
        public string NameonCard { get; set; }
        public string CardNumber { get; set; }
        public string ExpiryDateMMYY { get; set; }
        public string SecurityCode { get; set; }
        public string zipCode { get; set; }
        public bool ShippingUserContactAddress { get; set; }
        public string ShippingAddress { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime modified_at { get; set; }
        public bool IsActive { get; set; }
        public string AddedUserName { get; set; }
        public string ModifiedUserName { get; set; }
    }
}
