//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeStore1
{
    using System;
    
    public partial class SelectCartItem_BySessionID_1
    {
        public int CartItemID { get; set; }
        public int session_id { get; set; }
        public int product_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public string SKU { get; set; }
        public double amount { get; set; }
        public Nullable<int> quantity { get; set; }
        public string TotalAmount { get; set; }
    }
}
